### ISSUE TITLE
Instalacja środowiska symulacyjnego

### ISSUE THREAD

**Issue by xEdziu** [Hololens-PWr-Projekt/MESH#1]
# Każdy z was powinien mieć zainstalowane środowisko do emulacji i uruchamiania wirtalnych hololensów

[Link do tutoriala - instalacja emulacji](https://learn.microsoft.com/pl-pl/windows/mixed-reality/develop/advanced-concepts/using-the-hololens-emulator)
[Link do pobrania VS](https://visualstudio.microsoft.com/pl/downloads/)

## Czy wykonałeś/aś zadanie?

- [x] @MANDRW 
- [x] @szxxlc 
- [x] @ZuberRS03 
- [x] @MaksymilianWis 
- [x] @KasiaFedoruk

**Comment by MANDRW** [comment]
> # Każdy z was powinien mieć zainstalowane środowisko do emulacji i uruchamiania wirtalnych hololensów
> [Link do tutoriala - instalacja emulacji](https://learn.microsoft.com/pl-pl/windows/mixed-reality/develop/advanced-concepts/using-the-hololens-emulator) [Link do pobrania VS](https://visualstudio.microsoft.com/pl/downloads/)
> 
> ## Czy wykonałeś/aś zadanie?
> * [x ]  @MANDRW
> * [ ]  @szxxlc
> * [ ]  @ZuberRS03
> * [ ]  @MaksymilianWis
> * [ ]  @KasiaFedoruk

**Comment by MANDRW** [comment]
> # Każdy z was powinien mieć zainstalowane środowisko do emulacji i uruchamiania wirtalnych hololensów
> 
> [Link do tutoriala - instalacja emulacji](https://learn.microsoft.com/pl-pl/windows/mixed-reality/develop/advanced-concepts/using-the-hololens-emulator)
> [Link do pobrania VS](https://visualstudio.microsoft.com/pl/downloads/)
> 
> ## Czy wykonałeś/aś zadanie?
> 
> - [x] @MANDRW 
> - [ ] @szxxlc 
> - [ ] @ZuberRS03 
> - [ ] @MaksymilianWis 
> - [ ] @KasiaFedoruk

**Comment by xEdziu** [comment]
Po wykonaniu zadania prosze o wysłanie screena z emulatora tutaj w komentarzu!

**Comment by szxxlc** [comment]
B)
![Zrzut ekranu 2024-10-08 221649](https://github.com/user-attachments/assets/f16e561d-6fc6-4a62-9806-befb0adcf0d0)

**Comment by MaksymilianWis** [comment]
![image](https://github.com/user-attachments/assets/0b3fef63-ced0-46bc-8c47-e87fbb5b155d)
welp, zadanie wykonane, to że żadne inputy na interface nie działają to już inna sprawa

**Comment by xEdziu** [comment]
> ![image](https://github.com/user-attachments/assets/0b3fef63-ced0-46bc-8c47-e87fbb5b155d)
> welp, zadanie wykonane, to że żadne inputy na interface nie działają to już inna sprawa

Mam dokładnie to samo xd bede myślał dlaczego

**Comment by ZuberRS03** [comment]
![Image](https://github.com/user-attachments/assets/23dc201f-e1db-401c-8ae5-1e7bf5dd79b6)

**Comment by ZuberRS03** [comment]
![Image](https://github.com/user-attachments/assets/70291838-06c7-4040-bd77-3affe76d940e)

**Comment by xEdziu** [comment]
@MaksymilianWis mi zadziałało sterowanie, jak uruchomiłem emulator jako administrator. Sprawdź proszę jak u Ciebie

**Comment by MaksymilianWis** [comment]
Tylko adminem odpalam bo inaczej jakiś błąd wywalał i to było rozwiązanie

**Comment by MANDRW** [comment]
![Zrzut ekranu 2024-10-09 204125](https://github.com/user-attachments/assets/1acda9ac-d0fa-4bbe-8aa2-72f14a9a2eac)
dziala

**Comment by KasiaFedoruk** [comment]
![image](https://github.com/user-attachments/assets/6c2d3dfd-90da-4f3b-b5b3-2a064e4c56b8)
